
<robot name="planar_folding_assembly" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="box_size_x" value="0.1" />
  <xacro:property name="box_size_y" value="0.1" />
  <xacro:property name="box_size_z" value="0.1" />

  <link name="handle" >

    <collision>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${box_size_x} ${box_size_y} ${box_size_z}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${box_size_x} ${box_size_y} ${box_size_z}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <joint name="handle_joint" type="revolute">

    <physics>
      <provide_feedback>1</provide_feedback>
    </physics>

    <origin xyz="0 0 ${-box_size_z*1.2}" rpy="0 0 0" />
    <parent link="handle" />
    <child link="box" />
    <limit lower="0" upper="0" velocity="1" effort="1" />

  </joint>

  <link name="box">

    <collision>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${box_size_x} ${box_size_y} ${box_size_z}" />
      </geometry>
    </collision>

    <visual>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0" />
      <geometry>
        <box size="${box_size_x} ${box_size_y} ${box_size_z}" />
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="${box_size_x/2} ${box_size_y/2} ${box_size_z/2}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>

  </link>

  <gazebo>
    <plugin name="planar_folding_controller" filename="libgazebo_ros_planar_folding_assembly_controller.so">
    </plugin>
  </gazebo>

</robot>
